
version: 2
jobs:
  build:
    docker:
      - image: ocaml/opam2:alpine-3.9-ocaml-4.07
    steps:
      - run:
          name: Prepare
          command: sudo apk add m4 linux-headers
      - run:
          name: Install
          command: opam install dune ocamlfind core base ounit qcheck react ppx_deriving
      - checkout
      - run:
          name: Test
          command: eval $(opam env) && make test
