
version: 2
jobs:
  build:
    docker:
      - image: ocaml/opam2:alpine
    steps:
      - checkout
      - run:
          name: Prepare
          command: sudo apk add m4 linux-headers
      - run:
          name: Install
          command: opam install ocamlfind core base ounit qcheck react ppx_deriving
      - run:
          name: Test
          command: make test